[roslaunch][INFO] 2020-10-13 20:57:40,809: Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2020-10-13 20:57:40,811: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2020-10-13 20:57:40,811: roslaunch starting with args ['/opt/ros/noetic/bin/roslaunch', 'neurocar_circler', 'neurocar.launch']
[roslaunch][INFO] 2020-10-13 20:57:40,811: roslaunch env is environ({'ROS_VERSION': '1', 'GAZEBO_MASTER_URI': 'http://localhost:11345', 'PKG_CONFIG_PATH': '/home/rg/neuro_car_catkin/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig', 'ROS_PYTHON_VERSION': '3', 'HOSTNAME': '51cdf089c753', 'ROS_PACKAGE_PATH': '/home/rg/neuro_car_catkin/src:/opt/ros/noetic/share', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/rg/neuro_car_catkin/devel/share/common-lisp', 'PWD': '/home/rg/neuro_car_catkin', 'HOME': '/root', 'GAZEBO_PLUGIN_PATH': '/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:', 'LANG': 'C.UTF-8', 'GAZEBO_MODEL_DATABASE_URI': 'http://models.gazebosim.org', 'ROS_ETC_DIR': '/opt/ros/noetic/etc/ros', 'CMAKE_PREFIX_PATH': '/home/rg/neuro_car_catkin/devel:/opt/ros/noetic', 'GAZEBO_RESOURCE_PATH': '/usr/share/gazebo-11:', 'PYTHONPATH': '/opt/ros/noetic/lib/python3/dist-packages', 'TERM': 'xterm', 'SHLVL': '1', 'ROS_MASTER_URI': 'http://localhost:11311', 'LD_LIBRARY_PATH': '/home/rg/neuro_car_catkin/devel/lib:/opt/ros/noetic/lib:/usr/lib/x86_64-linux-gnu/gazebo-11/plugins', 'LC_ALL': 'C.UTF-8', 'GAZEBO_MODEL_PATH': '/usr/share/gazebo-11/models:', 'PATH': '/opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'ROS_ROOT': '/opt/ros/noetic/share/ros', 'ROS_DISTRO': 'noetic', 'OGRE_RESOURCE_PATH': '/usr/lib/x86_64-linux-gnu/OGRE-1.9.0', '_': '/opt/ros/noetic/bin/roslaunch', 'ROS_LOG_FILENAME': '/root/.ros/log/bb8e787a-0d96-11eb-9f7a-0242ac110002/roslaunch-51cdf089c753-37.log'})
[roslaunch][INFO] 2020-10-13 20:57:40,811: starting in server mode
[roslaunch.parent][INFO] 2020-10-13 20:57:40,811: starting roslaunch parent run
[roslaunch][INFO] 2020-10-13 20:57:40,811: loading roscore config file /opt/ros/noetic/etc/ros/roscore.xml
[roslaunch][INFO] 2020-10-13 20:57:41,092: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2020-10-13 20:57:41,092: loading config file /home/rg/neuro_car_catkin/src/neurocar_circler/launch/neurocar.launch
[roslaunch][ERROR] 2020-10-13 20:57:41,101: Resource not found: gazebo_ros
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/rg/neuro_car_catkin/src
ROS path [2]=/opt/ros/noetic/share
[roslaunch][ERROR] 2020-10-13 20:57:41,101: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2020-10-13 20:57:41,102: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 596, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 189, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 392, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 405, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 164, in _find
    res = _find_executable(
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/substitution_args.py", line 212, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 207, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: gazebo_ros
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/rg/neuro_car_catkin/src
ROS path [2]=/opt/ros/noetic/share

[rospy.core][INFO] 2020-10-13 20:57:41,102: signal_shutdown [atexit]
